export const countries = [
  { value: "afghanistan", label: "Afghanistan" },
  { value: "albania", label: "Albania" },
  { value: "algeria", label: "Algeria" },
  { value: "andorra", label: "Andorra" },
  { value: "angola", label: "Angola" },
  { value: "antigua_and_barbuda", label: "Antigua and Barbuda" },
  { value: "argentina", label: "Argentina" },
  { value: "armenia", label: "Armenia" },
  { value: "australia", label: "Australia" },
  { value: "austria", label: "Austria" },
  { value: "azerbaijan", label: "Azerbaijan" },
  { value: "bahamas", label: "Bahamas" },
  { value: "bahrain", label: "Bahrain" },
  { value: "bangladesh", label: "Bangladesh" },
  { value: "barbados", label: "Barbados" },
  { value: "belarus", label: "Belarus" },
  { value: "belgium", label: "Belgium" },
  { value: "belize", label: "Belize" },
  { value: "benin", label: "Benin" },
  { value: "bhutan", label: "Bhutan" },
  { value: "bolivia", label: "Bolivia" },
  { value: "bosnia_and_herzegovina", label: "Bosnia and Herzegovina" },
  { value: "botswana", label: "Botswana" },
  { value: "brazil", label: "Brazil" },
  { value: "brunei", label: "Brunei" },
  { value: "bulgaria", label: "Bulgaria" },
  { value: "burkina_faso", label: "Burkina Faso" },
  { value: "burundi", label: "Burundi" },
  { value: "cabo_verde", label: "Cabo Verde" },
  { value: "cambodia", label: "Cambodia" },
  { value: "cameroon", label: "Cameroon" },
  { value: "canada", label: "Canada" },
  { value: "central_african_republic", label: "Central African Republic" },
  { value: "chad", label: "Chad" },
  { value: "chile", label: "Chile" },
  { value: "china", label: "China" },
  { value: "colombia", label: "Colombia" },
  { value: "comoros", label: "Comoros" },
  { value: "costa_rica", label: "Costa Rica" },
  { value: "croatia", label: "Croatia" },
  { value: "cuba", label: "Cuba" },
  { value: "cyprus", label: "Cyprus" },
  { value: "czechia", label: "Czechia" },
  { value: "denmark", label: "Denmark" },
  { value: "djibouti", label: "Djibouti" },
  { value: "dominica", label: "Dominica" },
  { value: "dominican_republic", label: "Dominican Republic" },
  { value: "ecuador", label: "Ecuador" },
  { value: "egypt", label: "Egypt" },
  { value: "el_salvador", label: "El Salvador" },
  { value: "equatorial_guinea", label: "Equatorial Guinea" },
  { value: "eritrea", label: "Eritrea" },
  { value: "estonia", label: "Estonia" },
  { value: "eswatini", label: "Eswatini" },
  { value: "ethiopia", label: "Ethiopia" },
  { value: "fiji", label: "Fiji" },
  { value: "finland", label: "Finland" },
  { value: "france", label: "France" },
  { value: "gabon", label: "Gabon" },
  { value: "gambia", label: "Gambia" },
  { value: "georgia", label: "Georgia" },
  { value: "germany", label: "Germany" },
  { value: "ghana", label: "Ghana" },
  { value: "greece", label: "Greece" },
  { value: "grenada", label: "Grenada" },
  { value: "guatemala", label: "Guatemala" },
  { value: "guinea", label: "Guinea" },
  { value: "guinea_bissau", label: "Guinea-Bissau" },
  { value: "guyana", label: "Guyana" },
  { value: "haiti", label: "Haiti" },
  { value: "honduras", label: "Honduras" },
  { value: "hungary", label: "Hungary" },
  { value: "iceland", label: "Iceland" },
  { value: "india", label: "India" },
  { value: "indonesia", label: "Indonesia" },
  { value: "iran", label: "Iran" },
  { value: "iraq", label: "Iraq" },
  { value: "ireland", label: "Ireland" },
  { value: "israel", label: "Israel" },
  { value: "italy", label: "Italy" },
  { value: "jamaica", label: "Jamaica" },
  { value: "japan", label: "Japan" },
  { value: "jordan", label: "Jordan" },
  { value: "kazakhstan", label: "Kazakhstan" },
  { value: "kenya", label: "Kenya" },
  { value: "kiribati", label: "Kiribati" },
  { value: "north_korea", label: "Korea (North)" },
  { value: "south_korea", label: "Korea (South)" },
  { value: "kuwait", label: "Kuwait" },
  { value: "kyrgyzstan", label: "Kyrgyzstan" },
  { value: "laos", label: "Laos" },
  { value: "latvia", label: "Latvia" },
  { value: "lebanon", label: "Lebanon" },
  { value: "lesotho", label: "Lesotho" },
  { value: "liberia", label: "Liberia" },
  { value: "libya", label: "Libya" },
  { value: "liechtenstein", label: "Liechtenstein" },
  { value: "lithuania", label: "Lithuania" },
  { value: "luxembourg", label: "Luxembourg" },
  { value: "madagascar", label: "Madagascar" },
  { value: "malawi", label: "Malawi" },
  { value: "malaysia", label: "Malaysia" },
  { value: "maldives", label: "Maldives" },
  { value: "mali", label: "Mali" },
  { value: "malta", label: "Malta" },
  { value: "marshall_islands", label: "Marshall Islands" },
  { value: "mauritania", label: "Mauritania" },
  { value: "mauritius", label: "Mauritius" },
  { value: "mexico", label: "Mexico" },
  { value: "micronesia", label: "Micronesia" },
  { value: "moldova", label: "Moldova" },
  { value: "monaco", label: "Monaco" },
  { value: "mongolia", label: "Mongolia" },
  { value: "montenegro", label: "Montenegro" },
  { value: "morocco", label: "Morocco" },
  { value: "mozambique", label: "Mozambique" },
  { value: "namibia", label: "Namibia" },
  { value: "nauru", label: "Nauru" },
  { value: "nepal", label: "Nepal" },
  { value: "netherlands", label: "Netherlands" },
  { value: "new_zealand", label: "New Zealand" },
  { value: "nicaragua", label: "Nicaragua" },
  { value: "niger", label: "Niger" },
  { value: "nigeria", label: "Nigeria" },
  { value: "norway", label: "Norway" },
  { value: "oman", label: "Oman" },
  { value: "pakistan", label: "Pakistan" },
  { value: "palau", label: "Palau" },
  { value: "palestine", label: "Palestine" },
  { value: "panama", label: "Panama" },
  { value: "papua_new_guinea", label: "Papua New Guinea" },
  { value: "paraguay", label: "Paraguay" },
  { value: "peru", label: "Peru" },
  { value: "philippines", label: "Philippines" },
  { value: "poland", label: "Poland" },
  { value: "portugal", label: "Portugal" },
  { value: "qatar", label: "Qatar" },
  { value: "romania", label: "Romania" },
  { value: "russia", label: "Russia" },
  { value: "rwanda", label: "Rwanda" },
  { value: "saint_kitts_and_nevis", label: "Saint Kitts and Nevis" },
  { value: "saint_lucia", label: "Saint Lucia" },
  {
    value: "saint_vincent_and_the_grenadines",
    label: "Saint Vincent and the Grenadines",
  },
  { value: "samoa", label: "Samoa" },
  { value: "san_marino", label: "San Marino" },
  { value: "sao_tome_and_principe", label: "Sao Tome and Principe" },
  { value: "saudi_arabia", label: "Saudi Arabia" },
  { value: "senegal", label: "Senegal" },
  { value: "serbia", label: "Serbia" },
  { value: "seychelles", label: "Seychelles" },
  { value: "sierra_leone", label: "Sierra Leone" },
  { value: "singapore", label: "Singapore" },
  { value: "slovakia", label: "Slovakia" },
  { value: "slovenia", label: "Slovenia" },
  { value: "solomon_islands", label: "Solomon Islands" },
  { value: "somalia", label: "Somalia" },
  { value: "south_africa", label: "South Africa" },
  { value: "spain", label: "Spain" },
  { value: "sri_lanka", label: "Sri Lanka" },
  { value: "sudan", label: "Sudan" },
  { value: "suriname", label: "Suriname" },
  { value: "sweden", label: "Sweden" },
  { value: "switzerland", label: "Switzerland" },
  { value: "syria", label: "Syria" },
  { value: "taiwan", label: "Taiwan" },
  { value: "tajikistan", label: "Tajikistan" },
  { value: "tanzania", label: "Tanzania" },
  { value: "thailand", label: "Thailand" },
  { value: "timor_leste", label: "Timor-Leste" },
  { value: "togo", label: "Togo" },
  { value: "tonga", label: "Tonga" },
  { value: "trinidad_and_tobago", label: "Trinidad and Tobago" },
  { value: "tunisia", label: "Tunisia" },
  { value: "turkey", label: "Turkey" },
  { value: "turkmenistan", label: "Turkmenistan" },
  { value: "tuvalu", label: "Tuvalu" },
  { value: "uganda", label: "Uganda" },
  { value: "ukraine", label: "Ukraine" },
  { value: "united_arab_emirates", label: "United Arab Emirates" },
  { value: "united_kingdom", label: "United Kingdom" },
  { value: "united_states", label: "United States" },
  { value: "uruguay", label: "Uruguay" },
  { value: "uzbekistan", label: "Uzbekistan" },
  { value: "vanuatu", label: "Vanuatu" },
  { value: "venezuela", label: "Venezuela" },
  { value: "vietnam", label: "Vietnam" },
  { value: "yemen", label: "Yemen" },
  { value: "zambia", label: "Zambia" },
  { value: "zimbabwe", label: "Zimbabwe" },
];

export const countryCityData = {
  afghanistan: ["Kabul", "Kandahar", "Herat", "Mazar-i-Sharif"],
  albania: ["Tirana", "Durrës", "Vlorë", "Shkodër"],
  algeria: ["Algiers", "Oran", "Constantine", "Annaba"],
  andorra: ["Andorra la Vella", "Escaldes-Engordany"],
  angola: ["Luanda", "Huambo", "Lobito", "Benguela"],
  argentina: ["Buenos Aires", "Córdoba", "Rosario", "Mendoza"],
  australia: ["Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide"],
  austria: ["Vienna", "Salzburg", "Innsbruck", "Graz"],
  bangladesh: ["Dhaka", "Chittagong", "Khulna", "Rajshahi"],
  belgium: ["Brussels", "Antwerp", "Ghent", "Charleroi"],
  brazil: ["São Paulo", "Rio de Janeiro", "Brasília", "Salvador"],
  canada: ["Toronto", "Vancouver", "Montreal", "Calgary", "Ottawa"],
  china: ["Beijing", "Shanghai", "Guangzhou", "Shenzhen", "Wuhan"],
  egypt: ["Cairo", "Alexandria", "Giza", "Shubra El-Kheima"],
  france: ["Paris", "Marseille", "Lyon", "Toulouse", "Nice"],
  germany: ["Berlin", "Hamburg", "Munich", "Cologne", "Frankfurt"],
  india: ["Mumbai", "Delhi", "Bangalore", "Hyderabad", "Chennai"],
  indonesia: ["Jakarta", "Surabaya", "Bandung", "Medan", "Semarang"],
  iran: ["Tehran", "Mashhad", "Isfahan", "Karaj", "Shiraz"],
  iraq: ["Baghdad", "Basra", "Erbil", "Mosul", "Najaf"],
  ireland: ["Dublin", "Cork", "Galway", "Limerick"],
  italy: ["Rome", "Milan", "Naples", "Turin", "Palermo"],
  japan: ["Tokyo", "Osaka", "Yokohama", "Nagoya", "Sapporo"],
  kenya: ["Nairobi", "Mombasa", "Kisumu", "Nakuru", "Eldoret"],
  mexico: ["Mexico City", "Guadalajara", "Monterrey", "Puebla", "Tijuana"],
  nigeria: ["Lagos", "Abuja", "Kano", "Ibadan", "Port Harcourt"],
  pakistan: [
    "Karachi",
    "Lahore",
    "Islamabad",
    "Rawalpindi",
    "Faisalabad",
    "Multan",
  ],
  philippines: [
    "Manila",
    "Quezon City",
    "Davao City",
    "Cebu City",
    "Zamboanga City",
  ],
  russia: [
    "Moscow",
    "Saint Petersburg",
    "Novosibirsk",
    "Yekaterinburg",
    "Kazan",
  ],
  saudi_arabia: ["Riyadh", "Jeddah", "Mecca", "Medina", "Dammam"],
  south_africa: [
    "Johannesburg",
    "Cape Town",
    "Durban",
    "Pretoria",
    "Port Elizabeth",
  ],
  south_korea: ["Seoul", "Busan", "Incheon", "Daegu", "Daejeon"],
  spain: ["Madrid", "Barcelona", "Valencia", "Seville", "Zaragoza"],
  sri_lanka: ["Colombo", "Kandy", "Galle", "Jaffna", "Negombo"],
  thailand: ["Bangkok", "Chiang Mai", "Pattaya", "Phuket", "Nonthaburi"],
  turkey: ["Istanbul", "Ankara", "Izmir", "Bursa", "Adana"],
  ukraine: ["Kyiv", "Kharkiv", "Odessa", "Dnipro", "Lviv"],
  united_arab_emirates: ["Dubai", "Abu Dhabi", "Sharjah", "Ajman"],
  united_kingdom: ["London", "Manchester", "Birmingham", "Leeds", "Glasgow"],
  united_states: ["New York", "Los Angeles", "Chicago", "Houston", "Phoenix"],
  vietnam: ["Ho Chi Minh City", "Hanoi", "Da Nang", "Hai Phong", "Can Tho"],
};

export const gender = [
  { value: "male", label: "Male" },
  { value: "female", label: "Female" },
];

export const ageGroup = [
  { value: "20-30", label: "20-30" },
  { value: "40-50", label: "40-50" },
  { value: "50-60", label: "50-60" },
];

export const content = [
  { value: "VIDEO", label: "Video" },
  { value: "PHOTO", label: "Photo" },
];

export const industry = [
  { value: "app&tech", label: "App and Tech" },
  { value: "finance", label: "Finance" },
  { value: "healthcare", label: "Health Care" },
  { value: "education", label: "Education" },
  { value: "real_estate", label: "Real Estate" },
  { value: "retail", label: "Retail" },
  { value: "hourse", label: "Hourse" },
  { value: "apartment", label: "Apartment" },
  { value: "garden", label: "Garden" },
  { value: "car", label: "Car" },
  { value: "motorbike", label: "Motorbike" },
  { value: "bike", label: "Bike" },
  { value: "couple", label: "Couple" },
  { value: "baby", label: "Baby" },
  { value: "child", label: "Child" },
  { value: "parent", label: "Parent" },
  { value: "family", label: "Family" },
  { value: "friends", label: "Friends" },
  { value: "dog", label: "Dog" },
  { value: "cat", label: "Cat" },
];

export const responseTime = [
  { value: "10_minutes", label: "10 minutes" },
  { value: "20_minutes", label: "20 minutes" },
  { value: "30_minutes", label: "30 minutes" },
];

export const languages = [
  { value: "english", label: "English" },
  { value: "urdu", label: "Urdu" },
  { value: "spanish", label: "Spanish" },
  { value: "french", label: "French" },
  { value: "german", label: "German" },
  { value: "chinese", label: "Chinese" },
  { value: "japanese", label: "Japanese" },
  { value: "russian", label: "Russian" },
  { value: "italian", label: "Italian" },
  { value: "portuguese", label: "Portuguese" },
  { value: "hindi", label: "Hindi" },
  { value: "arabic", label: "Arabic" },
  { value: "bengali", label: "Bengali" },
  { value: "korean", label: "Korean" },
  { value: "turkish", label: "Turkish" },
  { value: "vietnamese", label: "Vietnamese" },
  { value: "polish", label: "Polish" },
  { value: "dutch", label: "Dutch" },
  { value: "thai", label: "Thai" },
  { value: "swedish", label: "Swedish" },
  { value: "greek", label: "Greek" },
  { value: "czech", label: "Czech" },
  { value: "hebrew", label: "Hebrew" },
  { value: "norwegian", label: "Norwegian" },
  { value: "danish", label: "Danish" },
  { value: "finnish", label: "Finnish" },
  { value: "hungarian", label: "Hungarian" },
  { value: "persian", label: "Persian" },
  { value: "ukrainian", label: "Ukrainian" },
  { value: "malay", label: "Malay" },
  { value: "romanian", label: "Romanian" },
  { value: "slovak", label: "Slovak" },
  { value: "indonesian", label: "Indonesian" },
  { value: "filipino", label: "Filipino" },
  { value: "swahili", label: "Swahili" },
];

export const industries = [
  "App & Tech",
  "Finance",
  "Healthcare",
  "Education",
  "Real Estate",
  "Retail",
  "Transportation",
  "Hospitality",
  "Manufacturing",
  "Agriculture",
  "Media & Entertainment",
  "Legal Services",
  "Construction",
  "E-commerce",
  "Marketing & Advertising",
  "Telecommunications",
  "Energy & Utilities",
];

export const industriesBrand = [
  // Fashion & Beauty
  "Fashion (Clothing, Accessories, Shoes)",
  "Beauty & Skincare",
  "Haircare (Products, Extensions, Salons)",
  "Cosmetics & Nails",

  // Lifestyle & Well-Being
  "Health & Wellness (Fitness, Yoga, Spa, Massages)",
  "Luxury & High-End Lifestyle",
  "Travel & Tourism (Hotels, Agencies, Experiences)",
  "Events & Entertainment (Weddings, Concerts)",

  // Tech & Digital
  "App & Tech (Mobile apps, SaaS, Startups)",
  "Crypto & Web3",
  "Gaming & eSports",

  // Food & Beverages
  "Restaurants & Cafés",
  "Food Delivery Services",
  "Wine & Spirits",
  "Healthy Food & Supplements",

  // Home & Décor
  "Real Estate & Property",
  "Furniture & Interior Design",
  "Home Appliances & Smart Home",

  // Mobility & Transportation
  "Cars & Auto (Cars, Bikes, EVs)",
  "Aviation & Luxury Transport",

  // Education & Services
  "E-learning & Coaching",
  "Personal Finance & Investment",
  "Legal & Business Services",

  // Other
  "Other",
];


export const equipment = [
  "Hourse",
  "Apartment",
  "Garden",
  "Car",
  "Motorbike",
  "Bike",
];

export const filming = [
  "Couple",
  "Baby",
  "Child",
  "Parent",
  "Family",
  "Friends",
];

export const pets = ["Dog", "Cat"];
