export const countries = [
  { value: "afghanistan", label: "Afghanistan" },
  { value: "albania", label: "Albania" },
  { value: "algeria", label: "Algeria" },
  { value: "andorra", label: "Andorra" },
  { value: "angola", label: "Angola" },
  { value: "antigua_and_barbuda", label: "Antigua and Barbuda" },
  { value: "argentina", label: "Argentina" },
  { value: "armenia", label: "Armenia" },
  { value: "australia", label: "Australia" },
  { value: "austria", label: "Austria" },
  { value: "azerbaijan", label: "Azerbaijan" },
  { value: "bahamas", label: "Bahamas" },
  { value: "bahrain", label: "Bahrain" },
  { value: "bangladesh", label: "Bangladesh" },
  { value: "barbados", label: "Barbados" },
  { value: "belarus", label: "Belarus" },
  { value: "belgium", label: "Belgium" },
  { value: "belize", label: "Belize" },
  { value: "benin", label: "Benin" },
  { value: "bhutan", label: "Bhutan" },
  { value: "bolivia", label: "Bolivia" },
  { value: "bosnia_and_herzegovina", label: "Bosnia and Herzegovina" },
  { value: "botswana", label: "Botswana" },
  { value: "brazil", label: "Brazil" },
  { value: "brunei", label: "Brunei" },
  { value: "bulgaria", label: "Bulgaria" },
  { value: "burkina_faso", label: "Burkina Faso" },
  { value: "burundi", label: "Burundi" },
  { value: "cabo_verde", label: "Cabo Verde" },
  { value: "cambodia", label: "Cambodia" },
  { value: "cameroon", label: "Cameroon" },
  { value: "canada", label: "Canada" },
  { value: "central_african_republic", label: "Central African Republic" },
  { value: "chad", label: "Chad" },
  { value: "chile", label: "Chile" },
  { value: "china", label: "China" },
  { value: "colombia", label: "Colombia" },
  { value: "comoros", label: "Comoros" },
  { value: "costa_rica", label: "Costa Rica" },
  { value: "croatia", label: "Croatia" },
  { value: "cuba", label: "Cuba" },
  { value: "cyprus", label: "Cyprus" },
  { value: "czechia", label: "Czechia" },
  { value: "denmark", label: "Denmark" },
  { value: "djibouti", label: "Djibouti" },
  { value: "dominica", label: "Dominica" },
  { value: "dominican_republic", label: "Dominican Republic" },
  { value: "ecuador", label: "Ecuador" },
  { value: "egypt", label: "Egypt" },
  { value: "el_salvador", label: "El Salvador" },
  { value: "equatorial_guinea", label: "Equatorial Guinea" },
  { value: "eritrea", label: "Eritrea" },
  { value: "estonia", label: "Estonia" },
  { value: "eswatini", label: "Eswatini" },
  { value: "ethiopia", label: "Ethiopia" },
  { value: "fiji", label: "Fiji" },
  { value: "finland", label: "Finland" },
  { value: "france", label: "France" },
  { value: "gabon", label: "Gabon" },
  { value: "gambia", label: "Gambia" },
  { value: "georgia", label: "Georgia" },
  { value: "germany", label: "Germany" },
  { value: "ghana", label: "Ghana" },
  { value: "greece", label: "Greece" },
  { value: "grenada", label: "Grenada" },
  { value: "guatemala", label: "Guatemala" },
  { value: "guinea", label: "Guinea" },
  { value: "guinea_bissau", label: "Guinea-Bissau" },
  { value: "guyana", label: "Guyana" },
  { value: "haiti", label: "Haiti" },
  { value: "honduras", label: "Honduras" },
  { value: "hungary", label: "Hungary" },
  { value: "iceland", label: "Iceland" },
  { value: "india", label: "India" },
  { value: "indonesia", label: "Indonesia" },
  { value: "iran", label: "Iran" },
  { value: "iraq", label: "Iraq" },
  { value: "ireland", label: "Ireland" },
  { value: "israel", label: "Israel" },
  { value: "italy", label: "Italy" },
  { value: "jamaica", label: "Jamaica" },
  { value: "japan", label: "Japan" },
  { value: "jordan", label: "Jordan" },
  { value: "kazakhstan", label: "Kazakhstan" },
  { value: "kenya", label: "Kenya" },
  { value: "kiribati", label: "Kiribati" },
  { value: "north_korea", label: "Korea (North)" },
  { value: "south_korea", label: "Korea (South)" },
  { value: "kuwait", label: "Kuwait" },
  { value: "kyrgyzstan", label: "Kyrgyzstan" },
  { value: "laos", label: "Laos" },
  { value: "latvia", label: "Latvia" },
  { value: "lebanon", label: "Lebanon" },
  { value: "lesotho", label: "Lesotho" },
  { value: "liberia", label: "Liberia" },
  { value: "libya", label: "Libya" },
  { value: "liechtenstein", label: "Liechtenstein" },
  { value: "lithuania", label: "Lithuania" },
  { value: "luxembourg", label: "Luxembourg" },
  { value: "madagascar", label: "Madagascar" },
  { value: "malawi", label: "Malawi" },
  { value: "malaysia", label: "Malaysia" },
  { value: "maldives", label: "Maldives" },
  { value: "mali", label: "Mali" },
  { value: "malta", label: "Malta" },
  { value: "marshall_islands", label: "Marshall Islands" },
  { value: "mauritania", label: "Mauritania" },
  { value: "mauritius", label: "Mauritius" },
  { value: "mexico", label: "Mexico" },
  { value: "micronesia", label: "Micronesia" },
  { value: "moldova", label: "Moldova" },
  { value: "monaco", label: "Monaco" },
  { value: "mongolia", label: "Mongolia" },
  { value: "montenegro", label: "Montenegro" },
  { value: "morocco", label: "Morocco" },
  { value: "mozambique", label: "Mozambique" },
  { value: "namibia", label: "Namibia" },
  { value: "nauru", label: "Nauru" },
  { value: "nepal", label: "Nepal" },
  { value: "netherlands", label: "Netherlands" },
  { value: "new_zealand", label: "New Zealand" },
  { value: "nicaragua", label: "Nicaragua" },
  { value: "niger", label: "Niger" },
  { value: "nigeria", label: "Nigeria" },
  { value: "norway", label: "Norway" },
  { value: "oman", label: "Oman" },
  { value: "pakistan", label: "Pakistan" },
  { value: "palau", label: "Palau" },
  { value: "palestine", label: "Palestine" },
  { value: "panama", label: "Panama" },
  { value: "papua_new_guinea", label: "Papua New Guinea" },
  { value: "paraguay", label: "Paraguay" },
  { value: "peru", label: "Peru" },
  { value: "philippines", label: "Philippines" },
  { value: "poland", label: "Poland" },
  { value: "portugal", label: "Portugal" },
  { value: "qatar", label: "Qatar" },
  { value: "romania", label: "Romania" },
  { value: "russia", label: "Russia" },
  { value: "rwanda", label: "Rwanda" },
  { value: "saint_kitts_and_nevis", label: "Saint Kitts and Nevis" },
  { value: "saint_lucia", label: "Saint Lucia" },
  {
    value: "saint_vincent_and_the_grenadines",
    label: "Saint Vincent and the Grenadines",
  },
  { value: "samoa", label: "Samoa" },
  { value: "san_marino", label: "San Marino" },
  { value: "sao_tome_and_principe", label: "Sao Tome and Principe" },
  { value: "saudi_arabia", label: "Saudi Arabia" },
  { value: "senegal", label: "Senegal" },
  { value: "serbia", label: "Serbia" },
  { value: "seychelles", label: "Seychelles" },
  { value: "sierra_leone", label: "Sierra Leone" },
  { value: "singapore", label: "Singapore" },
  { value: "slovakia", label: "Slovakia" },
  { value: "slovenia", label: "Slovenia" },
  { value: "solomon_islands", label: "Solomon Islands" },
  { value: "somalia", label: "Somalia" },
  { value: "south_africa", label: "South Africa" },
  { value: "spain", label: "Spain" },
  { value: "sri_lanka", label: "Sri Lanka" },
  { value: "sudan", label: "Sudan" },
  { value: "suriname", label: "Suriname" },
  { value: "sweden", label: "Sweden" },
  { value: "switzerland", label: "Switzerland" },
  { value: "syria", label: "Syria" },
  { value: "taiwan", label: "Taiwan" },
  { value: "tajikistan", label: "Tajikistan" },
  { value: "tanzania", label: "Tanzania" },
  { value: "thailand", label: "Thailand" },
  { value: "timor_leste", label: "Timor-Leste" },
  { value: "togo", label: "Togo" },
  { value: "tonga", label: "Tonga" },
  { value: "trinidad_and_tobago", label: "Trinidad and Tobago" },
  { value: "tunisia", label: "Tunisia" },
  { value: "turkey", label: "Turkey" },
  { value: "turkmenistan", label: "Turkmenistan" },
  { value: "tuvalu", label: "Tuvalu" },
  { value: "uganda", label: "Uganda" },
  { value: "ukraine", label: "Ukraine" },
  { value: "united_arab_emirates", label: "United Arab Emirates" },
  { value: "united_kingdom", label: "United Kingdom" },
  { value: "united_states", label: "United States" },
  { value: "uruguay", label: "Uruguay" },
  { value: "uzbekistan", label: "Uzbekistan" },
  { value: "vanuatu", label: "Vanuatu" },
  { value: "venezuela", label: "Venezuela" },
  { value: "vietnam", label: "Vietnam" },
  { value: "yemen", label: "Yemen" },
  { value: "zambia", label: "Zambia" },
  { value: "zimbabwe", label: "Zimbabwe" },
];

export const gender = [
  { value: "male", label: "Male" },
  { value: "female", label: "Female" },
  { value: "others", label: "Others" },
];

export const ageGroup = [
  { value: "20-30", label: "20-30" },
  { value: "40-50", label: "40-50" },
  { value: "50-60", label: "50-60" },
];

export const content = [
  { value: "photo", label: "Video" },
  { value: "video", label: "Photo" },
];

export const responseTime = [
  { value: "10 minutes", label: "10 minutes" },
  { value: "20 minutes", label: "20 minutes" },
  { value: "30 minutes", label: "30 minutes" },
  { value: "1 hour", label: "1 hour" },
  { value: "2 hour", label: "2 hour" },
  { value: "5 hour", label: "5 hour" },
  { value: "8 hour", label: "8 hour" },
  { value: "12 hour", label: "12 hour" },
  { value: "16 hour", label: "16 hour" },
  { value: "20 hour", label: "20 hour" },
  { value: "24 hour", label: "24 hour" },
];

export const languages = [
  { value: "english", label: "English" },
  { value: "urdu", label: "Urdu" },
  { value: "spanish", label: "Spanish" },
  { value: "french", label: "French" },
  { value: "german", label: "German" },
  { value: "chinese", label: "Chinese" },
  { value: "japanese", label: "Japanese" },
  { value: "russian", label: "Russian" },
  { value: "italian", label: "Italian" },
  { value: "portuguese", label: "Portuguese" },
  { value: "hindi", label: "Hindi" },
  { value: "arabic", label: "Arabic" },
  { value: "bengali", label: "Bengali" },
  { value: "korean", label: "Korean" },
  { value: "turkish", label: "Turkish" },
  { value: "vietnamese", label: "Vietnamese" },
  { value: "polish", label: "Polish" },
  { value: "dutch", label: "Dutch" },
  { value: "thai", label: "Thai" },
  { value: "swedish", label: "Swedish" },
  { value: "greek", label: "Greek" },
  { value: "czech", label: "Czech" },
  { value: "hebrew", label: "Hebrew" },
  { value: "norwegian", label: "Norwegian" },
  { value: "danish", label: "Danish" },
  { value: "finnish", label: "Finnish" },
  { value: "hungarian", label: "Hungarian" },
  { value: "persian", label: "Persian" },
  { value: "ukrainian", label: "Ukrainian" },
  { value: "malay", label: "Malay" },
  { value: "romanian", label: "Romanian" },
  { value: "slovak", label: "Slovak" },
  { value: "indonesian", label: "Indonesian" },
  { value: "filipino", label: "Filipino" },
  { value: "swahili", label: "Swahili" },
];

export const industries = [
  // Fashion & Beauty
  { value: "fashion", label: "Fashion" },
  { value: "accessories", label: "Accessories" },
  { value: "shoes", label: "Shoes" },
  { value: "beauty-skincare", label: "Beauty & Skincare" },
  { value: "makeup", label: "Makeup" },
  { value: "skincare", label: "Skincare" },
  { value: "perfumes", label: "Perfumes" },
  { value: "haircare", label: "Haircare" },
  { value: "hair-products", label: "Hair Products" },
  { value: "hair-extensions", label: "Hair Extensions" },
  { value: "hair-salons", label: "Hair Salons" },
  { value: "cosmetics-nails", label: "Cosmetics & Nails" },

  // Lifestyle & Well-Being
  { value: "health-wellness", label: "Health & Wellness" },
  { value: "fitness", label: "Fitness" },
  { value: "yoga", label: "Yoga" },
  { value: "spa", label: "Spa" },
  { value: "massages", label: "Massages" },
  { value: "luxury-lifestyle", label: "Luxury Lifestyle" },
  { value: "high-end-lifestyle", label: "High-End Lifestyle" },
  { value: "travel-tourism", label: "Travel & Tourism" },
  { value: "hotels", label: "Hotels" },
  { value: "travel-agencies", label: "Travel Agencies" },
  { value: "local-experiences", label: "Local Experiences" },
  { value: "events-entertainment", label: "Events & Entertainment" },
  { value: "weddings", label: "Weddings" },
  { value: "festivals", label: "Festivals" },
  { value: "concerts", label: "Concerts" },

  // Tech & Digital
  { value: "app-tech", label: "App & Tech" },
  { value: "mobile-apps", label: "Mobile Apps" },
  { value: "saas", label: "SaaS" },
  { value: "startups", label: "Startups" },
  { value: "crypto", label: "Crypto" },
  { value: "web3", label: "Web3" },
  { value: "gaming", label: "Gaming" },
  { value: "esports", label: "eSports" },

  // Food & Beverages
  { value: "restaurants", label: "Restaurants" },
  { value: "cafes", label: "Cafés" },
  { value: "food-delivery", label: "Food Delivery Services" },
  { value: "wine-spirits", label: "Wine & Spirits" },
  { value: "healthy-food", label: "Healthy Food" },
  { value: "supplements", label: "Supplements" },

  // Home & Décor
  { value: "real-estate", label: "Real Estate & Property" },
  { value: "furniture", label: "Furniture" },
  { value: "interior-design", label: "Interior Design" },
  { value: "home-appliances", label: "Home Appliances" },
  { value: "smart-home", label: "Smart Home" },

  // Mobility & Transportation
  { value: "cars", label: "Cars" },
  { value: "motorbikes", label: "Motorbikes" },
  { value: "electric-scooters", label: "Electric Scooters" },
  { value: "evs", label: "EVs" },
  { value: "aviation", label: "Aviation" },
  { value: "luxury-transport", label: "Luxury Transport" },

  // Education & Services
  { value: "e-learning", label: "E-learning" },
  { value: "coaching", label: "Coaching" },
  { value: "personal-finance", label: "Personal Finance" },
  { value: "investment", label: "Investment" },
  { value: "legal-services", label: "Legal Services" },
  { value: "business-services", label: "Business Services" },

  // Other
  { value: "other", label: "Other" },
];

export const equipment = [
  { label: "Hourse", value: "hourse" },
  { label: "Apartment", value: "apartment" },
  { label: "Garden", value: "garden" },
  { label: "Car", value: "car" },
  { label: "Motorbike", value: "motorbike" },
  { label: "Bike", value: "bike" },
];

export const filming = [
  { label: "Couple", value: "couple" },
  { label: "Baby", value: "baby" },
  { label: "Child", value: "child" },
  { label: "Parent", value: "parent" },
  { label: "Family", value: "family" },
  { label: "Friends", value: "friends" },
];

export const pets = [
  { label: "Dog", value: "dog" },
  { label: "Cat", value: "cat" },
];
